//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace 小型BBS管理系统.Pages {
    
    
    public partial class Admin {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new 小型BBS管理系统.Pages.AdminBase Master {
            get {
                return ((小型BBS管理系统.Pages.AdminBase)(base.Master));
            }
        }
    }
}
